# Generated by Django 4.2.1 on 2023-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('periodo', models.CharField(max_length=7, verbose_name='Periodo')),
                ('disciplina', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Nota')),
                ('situacao', models.CharField(max_length=1, verbose_name='Situação')),
            ],
        ),
    ]
