# Generated by Django 4.2.1 on 2023-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='situacao',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado')], max_length=1, verbose_name='Situação'),
        ),
    ]
