# Generated by Django 4.2.1 on 2023-06-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_matricula_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='situacao',
        ),
    ]
