# Generated by Django 4.2.1 on 2023-07-14 23:29

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='alunos', variations={'thumb': (124, 124)}, verbose_name='Imagem')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('rg', models.CharField(max_length=50, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('curso', models.CharField(max_length=50, verbose_name='Curso')),
                ('datanascimento', models.DateField(verbose_name='Data de nascimento')),
                ('dataingresso', models.DateField(verbose_name='Data de ingresso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
